/**
 * What every displayed value actually is, and where it came from.
 *
 * Two independent questions, and the UI must answer both because neither
 * answers the other:
 *
 *   1. KIND  - is this number a sensor reading, arithmetic on sensor readings,
 *              or the output of a hand-tuned model?
 *   2. ORIGIN - is the underlying data from physical hardware, a research
 *              dataset, or a synthetic simulation?
 *
 * A `MEASURED` field on `SIMULATED` data is not a measurement of anything. That
 * is precisely why both labels are shown: tagging voltage as MEASURED while the
 * fleet is synthetic would be the more misleading of the two half-truths, and
 * this project already shipped a dashboard that implied validation it did not
 * have (see docs/architecture_diagram_spec.md).
 *
 * This file is the single source of truth. A component that displays a value
 * without a matching entry here should fail the lookup loudly rather than
 * render an unlabelled number - see `describe`.
 */

export const KIND = {
  MEASURED: 'MEASURED',
  CALCULATED: 'CALCULATED',
  MODEL: 'MODEL-DERIVED',
};

export const ORIGIN = {
  LIVE: 'LIVE HARDWARE',
  DATASET: 'DATASET REPLAY',
  SIMULATED: 'SIMULATED',
};

/**
 * Origin metadata. `reachable: false` means this project has never produced
 * data in that state - stated rather than hidden, because an unreachable state
 * that looks available is worse than one that is labelled honestly.
 */
export const ORIGINS = {
  [ORIGIN.LIVE]: {
    tone: 'live',
    reachable: false,
    blurb:
      'Telemetry read from a physical rig over serial. No board has ever been ' +
      'connected to this project, so nothing you can see here is in this state.',
  },
  [ORIGIN.DATASET]: {
    tone: 'dataset',
    reachable: true,
    blurb:
      'Recorded telemetry replayed from a CAN log or a serial capture. Real ' +
      'measurements, recorded elsewhere, on cells this project did not cycle.',
  },
  [ORIGIN.SIMULATED]: {
    tone: 'sim',
    reachable: true,
    blurb:
      'Synthetic telemetry generated by this project. No cell exists. Every ' +
      'value below describes the simulator, not a battery.',
  },
};

/**
 * Field vocabulary.
 *
 * `definition` says what the number is; `caveat` says what it is not. The
 * caveats are not hedging - each one records a specific documented limitation,
 * and the ADR or report section that establishes it.
 */
export const FIELDS = {
  voltage_v: {
    kind: KIND.MEASURED,
    label: 'Terminal voltage',
    unit: 'V',
    definition: 'Cell terminal voltage as reported by the source.',
  },
  current_a: {
    kind: KIND.MEASURED,
    label: 'Current',
    unit: 'A',
    definition: 'Signed current. Negative is discharge.',
  },
  temperature_c: {
    kind: KIND.MEASURED,
    label: 'Temperature',
    unit: '°C',
    definition: 'Cell surface temperature as reported by the source.',
  },
  soc: {
    kind: KIND.CALCULATED,
    label: 'State of charge',
    unit: '%',
    definition:
      'Percent, 0-100. On a serial rig this is coulomb-counted by the firmware ' +
      'and drifts without an absolute reference.',
    caveat:
      'Not a measurement. Capacity does not depend on it, so SOC drift ' +
      'degrades the behaviour flags and leaves state of health untouched.',
  },
  capacity_ah: {
    kind: KIND.CALCULATED,
    label: 'Discharge capacity',
    unit: 'Ah',
    definition:
      'Charge integrated over a complete discharge phase (coulomb counting).',
    caveat:
      'Only comparable across equal depths of discharge, which is why partial ' +
      'cycles are excluded rather than scaled.',
  },
  avg_temp: {
    kind: KIND.CALCULATED,
    label: 'Mean temperature',
    unit: '°C',
    definition: 'Arithmetic mean of temperature over the battery’s rows.',
  },
  stress_score: {
    kind: KIND.MODEL,
    label: 'Stress score',
    unit: '0-100',
    definition:
      'Weighted sum of five binary behaviour flags. Weights are hand-picked, ' +
      'ordered by assumed severity.',
    caveat:
      'Not calibrated against measured degradation. The weights were chosen, ' +
      'not fitted.',
  },
  health_index: {
    kind: KIND.MODEL,
    label: 'Health index',
    unit: '0-100',
    definition:
      'Hand-weighted composite of mean temperature, deep-discharge duration, ' +
      'fast-charge duration and mean SOC.',
    caveat:
      'NOT state of health. SOH is measured capacity over rated capacity; this ' +
      'is a rule-based score that never sees a capacity measurement. It showed ' +
      'no significant relationship with real capacity fade (p > 0.13, n = 33).',
  },
  risk_score: {
    kind: KIND.MODEL,
    label: 'Risk score',
    unit: '0-100',
    definition: 'Sum of six step-function terms over the battery summary.',
    caveat:
      'The terms are coarse step functions. A 7x change in mean stress and 80 ' +
      'aggressive-discharge events can leave this figure unchanged, because ' +
      'both move within one step (cut points at 50 and 100).',
  },
  rul_cycles: {
    kind: KIND.MODEL,
    label: 'RUL',
    unit: 'cycles',
    definition:
      'An unvalidated 1000-cycle base life scaled by remaining health and an ' +
      'Equivalent Aging Factor.',
    caveat:
      'Not a prediction validated against observed failure, and not a ' +
      'measurement. The EAF reuses temperature, deep-discharge and fast-charge ' +
      'exposure that are already inside the health index it also depends on, ' +
      'so those are double-counted (documented, unfixed - see ADR 0003 and ' +
      'src/bms/rul/rul_estimation.py).',
  },
  equivalent_aging_factor: {
    kind: KIND.MODEL,
    label: 'Equivalent aging factor',
    unit: '×',
    definition: 'Dimensionless multiplier applied to the base cycle life.',
    caveat: 'Hand-picked weights; double-counts its inputs. See rul_cycles.',
  },
  failure_likelihood: {
    kind: KIND.MODEL,
    label: 'Failure likelihood',
    unit: '%',
    definition: 'A monotone relabel of the health index.',
    caveat:
      'Not a probability. Nothing here is calibrated against observed failures, ' +
      'so it does not mean “this fraction of such batteries fail”.',
  },
  twin_state: {
    kind: KIND.MODEL,
    label: 'Twin state',
    unit: '',
    definition: 'A banded relabel of the health index.',
    caveat:
      'A 1:1 relabel of health_index thresholds - it carries no information ' +
      'the health index does not already carry (docs/digital_twin.md).',
  },
  risk_level: {
    kind: KIND.MODEL,
    label: 'Risk level',
    unit: '',
    definition: 'A banded relabel of the risk score.',
    caveat: 'Inherits the step-function coarseness of risk_score.',
  },
  replacement_policy: {
    kind: KIND.MODEL,
    label: 'Policy',
    unit: '',
    definition: 'A banded relabel of rul_cycles.',
    caveat: 'Inherits every caveat of rul_cycles, including the double-count.',
  },
  soh: {
    kind: KIND.CALCULATED,
    label: 'State of health',
    unit: 'fraction',
    definition:
      'Measured discharge capacity divided by the cell’s reference capacity.',
    caveat:
      'Computed only where real cycling data provides a capacity measurement. ' +
      'It is NOT health_index and the two must not be read as the same ' +
      'quantity.',
  },
};

/** Look up a field, or return a loud placeholder rather than an unlabelled number. */
export function describe(field) {
  const entry = FIELDS[field];
  if (entry) return entry;
  return {
    kind: 'UNCLASSIFIED',
    label: field,
    unit: '',
    definition:
      'This field has no provenance entry. Add one in client/src/provenance.js ' +
      'before displaying it — an unlabelled number is the thing this module exists to prevent.',
  };
}

export function kindTone(kind) {
  if (kind === KIND.MEASURED) return 'measured';
  if (kind === KIND.CALCULATED) return 'calculated';
  if (kind === KIND.MODEL) return 'model';
  return 'unclassified';
}
