"""Ablations and a shuffle control for the NASA SOH benchmark.

    python scripts/run_ablation_study.py

Writes `reports/metrics/ablation/`. Answers three questions a reviewer asks of
the benchmark table, using the same harness, folds and metric:

1. FEATURE ABLATION. XGBoost on cycle number only, on behaviour features
   only (no cycle number), and on all seven. How much of the skill is age?
2. SHUFFLE CONTROL. Each cell's capacity sequence is randomly permuted
   against its features (seed fixed), destroying the time relationship while
   keeping every cell's values. A harness that is not manufacturing skill
   must then score at or below zero under leave-one-cohort-out.
3. The age_linear baseline is run on the shuffled frame too, as the
   control's own reference.

Uses the committed `reports/metrics/continuous_model_training_data.csv`, so
it runs on a fresh clone. Each run shells out to run_benchmark_study.py so the
harness is exactly the published one.
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
DATA = REPO / "reports" / "metrics" / "continuous_model_training_data.csv"
PUBLISHED = REPO / "reports" / "metrics" / "benchmark_results.csv"
OUT = REPO / "reports" / "metrics" / "ablation"
SHUFFLE_SEED = 20261005
BEHAVIOUR = ["avg_temp", "max_temp", "avg_stress", "deep_discharge_duration",
             "aggressive_discharge_count", "avg_soc"]
COLUMNS = ["lobo_mae", "loco_mae", "lobo_r2", "loco_r2", "loco_r2_ci_low", "loco_r2_ci_high"]


def _run(name: str, data: Path, methods: list[str], features: list[str] | None, tmp: Path) -> pd.DataFrame:
    out = tmp / name
    cmd = [sys.executable, str(REPO / "scripts" / "run_benchmark_study.py"),
           "--data", str(data), "--targets", "soh", "--methods", *methods, "--out", str(out)]
    if features:
        cmd += ["--features", *features]
    env = {**os.environ, "PYTHONPATH": str(REPO), "LOKY_MAX_CPU_COUNT": "2"}
    subprocess.run(cmd, check=True, cwd=REPO, env=env, capture_output=True)
    frame = pd.read_csv(out / "benchmark_results.csv")
    frame.insert(0, "run", name)
    return frame[["run", "method", *COLUMNS]]


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    rows = []
    published = pd.read_csv(PUBLISHED)
    full = published[published["method"].isin(["xgboost", "age_linear"])].copy()
    full.insert(0, "run", "all features (published)")
    rows.append(full[["run", "method", *COLUMNS]])

    with tempfile.TemporaryDirectory() as tmp_dir:
        tmp = Path(tmp_dir)
        rows.append(_run("cycle number only", DATA, ["xgboost"], ["cycle"], tmp))
        rows.append(_run("behaviour only, no cycle", DATA, ["xgboost"], BEHAVIOUR, tmp))

        shuffled = pd.read_csv(DATA)
        rng = np.random.default_rng(SHUFFLE_SEED)
        shuffled["capacity_ah"] = shuffled.groupby("cell_id")["capacity_ah"].transform(
            lambda s: rng.permutation(s.to_numpy()))
        shuffled_path = tmp / "shuffled.csv"
        shuffled.to_csv(shuffled_path, index=False)
        rows.append(_run("SHUFFLED in time (control)", shuffled_path,
                         ["xgboost", "age_linear"], None, tmp))

    table = pd.concat(rows, ignore_index=True)
    table.to_csv(OUT / "ablation_results.csv", index=False)
    lines = [
        "# Feature ablation and shuffle control, NASA SOH benchmark",
        "",
        "Generated by `scripts/run_ablation_study.py`. Same harness, folds and "
        "metric as `benchmark_results.csv`: 31 cells, 9 cohorts, R² against the "
        "training-fold mean, 95% bootstrap interval over LOCO folds.",
        "",
        "```",
        table.round(3).to_string(index=False),
        "```",
        "",
        "Reading it:",
        "",
        "- Neither half transfers alone. XGBoost on cycle number only, and on "
        "behaviour features only, both score below zero under LOCO; only the "
        "combination reaches the published point estimate, and its interval "
        "still overlaps the others.",
        "- The linear age baseline (`age_linear`) beats XGBoost on cycle number "
        "alone under LOCO: trees cannot extrapolate cycle count to an unseen "
        "cohort, a straight line can.",
        "- With each cell's capacity shuffled in time, every LOCO interval lies "
        "at or below zero. The harness does not produce skill where there is "
        "none. Residual LOBO skill for XGBoost on the shuffled frame is per-cell "
        "level memorisation: a cell's mean capacity survives the shuffle.",
    ]
    (OUT / "ablation_report.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(table.round(3).to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
