"""Does resistance from the load step track the cycler's resistance over life?

    python scripts/run_resistance_study.py

Reads the telemetry cache built by run_field_soh_study.py and writes
`reports/metrics/calce_resistance/`.

The field SOH path estimates resistance from the rest-to-load voltage step
(health/field_soh.py) and now reports it - resistance growth is power fade,
the part of health capacity does not show. Before the report card states it,
this checks it against the Arbin cycler's own Internal_Resistance column,
which the BMS never sees.

Per cell, over the discharges both measure:
  - Spearman correlation between the two resistance series across life
  - growth: median of the last 25 discharges over the first 25, for each

The step value is APPARENT resistance (ohmic plus early polarisation), so its
level is expected to differ from the cycler's; what matters is whether it
moves the same way.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.bms.health.field_soh import curves_from_telemetry  # noqa: E402
from src.bms.telemetry.cycles import cycles_to_frame, measure_cycles  # noqa: E402

CACHE = Path("data/interim/calce_telemetry")
OUT = Path("reports/metrics/calce_resistance")
REST = 0.02
EDGE = 25


def cell_row(cell: str) -> dict:
    tel = pd.read_parquet(CACHE / f"{cell}.parquet")
    d = cycles_to_frame(measure_cycles(tel, cell, rest_threshold_a=REST), complete_only=False)
    _, steps = curves_from_telemetry(tel, d, cell, REST)
    t = tel["test_time_s"].to_numpy(float)
    r = pd.to_numeric(tel.get("resistance_ohm"), errors="coerce").to_numpy(float)
    arbin = []
    for row in d.itertuples():
        a, b = np.searchsorted(t, row.start_time_s), np.searchsorted(t, row.end_time_s, "right")
        seg = r[a:b]
        seg = seg[np.isfinite(seg) & (seg > 0)]
        arbin.append(float(np.median(seg)) if len(seg) else np.nan)
    both = steps.assign(r_cycler=arbin[: len(steps)]).dropna(subset=["r_step_ohm", "r_cycler"])
    if len(both) < 2 * EDGE:
        return {"cell_id": cell, "n": len(both), "refusal": "too few discharges with both values"}
    rho = float(spearmanr(both["r_step_ohm"], both["r_cycler"]).statistic)
    g_step = both["r_step_ohm"].tail(EDGE).median() / both["r_step_ohm"].head(EDGE).median()
    g_cyc = both["r_cycler"].tail(EDGE).median() / both["r_cycler"].head(EDGE).median()
    return {"cell_id": cell, "n": len(both), "spearman": round(rho, 3),
            "step_r_start": round(float(both["r_step_ohm"].head(EDGE).median()), 4),
            "cycler_r_start": round(float(both["r_cycler"].head(EDGE).median()), 4),
            "growth_step": round(float(g_step), 3), "growth_cycler": round(float(g_cyc), 3),
            "same_direction": bool((g_step - 1) * (g_cyc - 1) > 0), "refusal": ""}


def main() -> int:
    rows = [cell_row(p.stem) for p in sorted(CACHE.glob("*.parquet"))]
    table = pd.DataFrame(rows)
    OUT.mkdir(parents=True, exist_ok=True)
    table.to_csv(OUT / "resistance_per_cell.csv", index=False)
    ok = table[table["refusal"] == ""]
    lines = [
        "# Step resistance against the cycler's resistance",
        "",
        "Generated by `scripts/run_resistance_study.py`.",
        "",
        f"{len(ok)} cells with enough discharges carrying both values. "
        f"Median Spearman correlation across life: {ok['spearman'].median():.2f}; "
        f"growth in the same direction on {int(ok['same_direction'].sum())} of {len(ok)}; "
        f"median growth {ok['growth_step'].median():.2f}x (step) vs "
        f"{ok['growth_cycler'].median():.2f}x (cycler).",
        "",
        "```",
        table.to_string(index=False),
        "```",
    ]
    (OUT / "resistance_report.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines[4:6]))
    print(table.to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
